### ISSUE TITLE
For loop in ruby vs js

### ISSUE THREAD

**Issue by nickangtc** [gauthamchandra/learning-ruby-from-js#5]
Hey just wanted to point out that a `for x in (0..100)` in Ruby is not the same as `for (let x...)` loop. The difference is in the ability to increment `x` in JS but not Ruby:

```js
// javascript
for (let i = 0; i < 100; i++) {
  console.log(i)
  i += 3
}
// => prints 0, 4, 8, 12...
```

```rb
# ruby
for i in (0..100)
  p i
  i += 3
end
# => prints 0 to 100
```

**Comment by gauthamchandra** [comment]
Ah you're totally right of course. I will fix shortly! 

(Sorry for the late response 😅 )

**Comment by gauthamchandra** [comment]
Fixed 👍
