### ISSUE TITLE
Minor correction

### ISSUE THREAD

**Issue by dep** [gauthamchandra/learning-ruby-from-js#8]
Using the yield keyword you can invoke code blocks and pass it arguments as if they were functions. Unless the blocks are specified as arguments, they are outside the parentheses. See below:

```ruby
def foo(greeting)
	puts 'Inside the function foo'
	yield(greeting)
	puts 'Back inside the function foo'
end
foo("Top of the mornin to ya!") { |greeting| puts "#{greeting} John" }
```

## Expected

```
Inside the function foo
Top of the mornin to ya! John
Back inside the function foo
```

## Actual

```
Inside the function foo
Top of the mornin to ya John
Back inside the function foo
```

You could change

```ruby
foo("Top of the mornin to ya!") { |greeting| puts "#{greeting} John" }
```

to

```ruby
foo("Top of the mornin to ya") { |greeting| puts "#{greeting} John" }
```

**Comment by dep** [comment]
It might also be helpful to note for a newbie that `|greeting|` could be anything you want it to be (having it coincidentally be the same as the variable of the `func` is a little bit confusing at first.  Just a note that `|pickes| puts "#{pickles} John"` would return the same result :)

**Comment by gauthamchandra** [comment]
Good catch. Fixing now 👍🏼 

Thanks for reporting!

**Comment by dep** [comment]
Thank you! And thanks for the excellent guide.
